#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#
# Copyleft (c) by Denis Astahov
#--------------------------------------------------------------
version: 0.1

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID    : "314682408916"
    ECR_REPO_NAME     : "task-21"
    ECR_IMAGE_TAG     : "latest"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 314682408916.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_ID=$(git rev-parse --short HEAD)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t task-21-nginx:$ECR_IMAGE_TAG /nginx
      - docker build -t task-21-apche:$ECR_IMAGE_TAG /apache
      - docker tag task-21-nginx:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/task-21-nginx:$ECR_IMAGE_TAG
      - docker tag task-21-apache:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/task-21-apache:$ECR_IMAGE_TAG
      

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/task-21-nginx:$ECR_IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/task-21-apache:$ECR_IMAGE_TAG
      