#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#
# Copyleft (c) by Denis Astahov
#--------------------------------------------------------------
version: 0.1

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID    : "314682408916"
    ECR_REPO_NAME     : "task-21"
    ECR_IMAGE_TAG     : "latest"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 314682408916.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t task-21-nginx:latest nginx
      - docker build -t task-21-apache:latest apache
      - docker tag task-21-nginx:latest 314682408916.dkr.ecr.us-east-1.amazonaws.com/task-21:nginx-app-latest
      - docker tag task-21-apache:latest 314682408916.dkr.ecr.us-east-1.amazonaws.com/task-21:apache-app-latest
      

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 314682408916.dkr.ecr.us-east-1.amazonaws.com/task-21:nginx-app-latest
      - docker push 314682408916.dkr.ecr.us-east-1.amazonaws.com/task-21:apache-app-latest

artifacts:
    files: imagedefinitions.json
      